In [12]:
import numpy as np

data = np.genfromtxt(
    "deliveries.csv",
    delimiter=",",
    dtype=str,
    skip_header=1
)

print("Shape:", data.shape)

Shape: (260920, 17)


In [13]:
match_id = data[:, 0].astype(int)
batting_team = data[:, 2]
over = data[:, 4].astype(int)
batter = data[:, 6]
bowler = data[:, 7]
batsman_runs = data[:, 9].astype(int)

print("Columns extracted ")

Columns extracted 


In [14]:
print(match_id[:5])
print(batter[:5])
print(batsman_runs[:5])
print(over[:5])

[335982 335982 335982 335982 335982]
['SC Ganguly' 'BB McCullum' 'BB McCullum' 'BB McCullum' 'BB McCullum']
[0 0 0 0 0]
[0 0 0 0 0]


In [15]:
# Task 1: Total Runs per Match

unique_matches = np.unique(match_id)

total_runs_per_match = np.array([
    (m, np.sum(batsman_runs[match_id == m]))
    for m in unique_matches
])

# Show first 5 results
total_runs_per_match[:5]

array([[335982,    268],
       [335983,    430],
       [335984,    244],
       [335985,    315],
       [335986,    184]])

In [16]:
# Task 2: Top 5 Batters

players = np.unique(batter)

# Total runs per player
runs_per_player = np.array([
    np.sum(batsman_runs[batter == p])
    for p in players
])

# Get indices of top 5 players (descending order)
top_indices = np.argsort(runs_per_player)[::-1][:5]

# Final result
top_5_batters = list(zip(players[top_indices], runs_per_player[top_indices]))

top_5_batters

[(np.str_('V Kohli'), np.int64(8014)),
 (np.str_('S Dhawan'), np.int64(6769)),
 (np.str_('RG Sharma'), np.int64(6630)),
 (np.str_('DA Warner'), np.int64(6567)),
 (np.str_('SK Raina'), np.int64(5536))]

In [17]:
# Task 3: Strike Rate

players = np.unique(batter)

# Total runs per player
total_runs = np.array([
    np.sum(batsman_runs[batter == p])
    for p in players
])

# Balls faced per player
balls_faced = np.array([
    np.sum(batter == p)
    for p in players
])

# Strike rate calculation
strike_rates = (total_runs / balls_faced) * 100

# Combine results
strike_rate_result = list(zip(players, strike_rates))

# Show first 5
strike_rate_result[:5]

[(np.str_('A Ashish Reddy'), np.float64(142.85714285714286)),
 (np.str_('A Badoni'), np.float64(125.54455445544555)),
 (np.str_('A Chandila'), np.float64(57.14285714285714)),
 (np.str_('A Chopra'), np.float64(70.66666666666667)),
 (np.str_('A Choudhary'), np.float64(125.0))]

In [18]:
# Task 4: Economy Rate of Bowlers

bowlers = np.unique(bowler)

# Total runs conceded per bowler
runs_conceded = np.array([
    np.sum(batsman_runs[bowler == b])
    for b in bowlers
])

# Total balls bowled per bowler
balls_bowled = np.array([
    np.sum(bowler == b)
    for b in bowlers
])

# Convert balls to overs
overs = balls_bowled / 6

# Economy rate
economy_rate = runs_conceded / overs

# Combine results
economy_result = list(zip(bowlers, economy_rate))

# Show first 5
economy_result[:5]

[(np.str_('A Ashish Reddy'), np.float64(8.577777777777778)),
 (np.str_('A Badoni'), np.float64(8.639999999999999)),
 (np.str_('A Chandila'), np.float64(6.205128205128205)),
 (np.str_('A Choudhary'), np.float64(7.611111111111111)),
 (np.str_('A Dananjaya'), np.float64(11.04))]