In [12]:
import numpy as np

data = np.genfromtxt(
    "deliveries.csv",
    delimiter=",",
    dtype=str,
    skip_header=1
)

print("Shape:", data.shape)

Shape: (260920, 17)


In [13]:
match_id = data[:, 0].astype(int)
batting_team = data[:, 2]
over = data[:, 4].astype(int)
batter = data[:, 6]
bowler = data[:, 7]
batsman_runs = data[:, 9].astype(int)

print("Columns extracted ")

Columns extracted 


In [14]:
print(match_id[:5])
print(batter[:5])
print(batsman_runs[:5])
print(over[:5])

[335982 335982 335982 335982 335982]
['SC Ganguly' 'BB McCullum' 'BB McCullum' 'BB McCullum' 'BB McCullum']
[0 0 0 0 0]
[0 0 0 0 0]


In [15]:
# Task 1: Total Runs per Match

unique_matches = np.unique(match_id)

total_runs_per_match = np.array([
    (m, np.sum(batsman_runs[match_id == m]))
    for m in unique_matches
])

# Show first 5 results
total_runs_per_match[:5]

array([[335982,    268],
       [335983,    430],
       [335984,    244],
       [335985,    315],
       [335986,    184]])

In [16]:
# Task 2: Top 5 Batters

players = np.unique(batter)

# Total runs per player
runs_per_player = np.array([
    np.sum(batsman_runs[batter == p])
    for p in players
])

# Get indices of top 5 players (descending order)
top_indices = np.argsort(runs_per_player)[::-1][:5]

# Final result
top_5_batters = list(zip(players[top_indices], runs_per_player[top_indices]))

top_5_batters

[(np.str_('V Kohli'), np.int64(8014)),
 (np.str_('S Dhawan'), np.int64(6769)),
 (np.str_('RG Sharma'), np.int64(6630)),
 (np.str_('DA Warner'), np.int64(6567)),
 (np.str_('SK Raina'), np.int64(5536))]